services:
  db:
    image: postgres:16-alpine
    container_name: worktracker-db
    environment:
      POSTGRES_DB: worktracker
      POSTGRES_USER: worktracker_user
      POSTGRES_PASSWORD: worktracker_pass
    ports:
      - "5432:5432"

  backend:
    build: ./BackEnd/WorkTrackerD424
    container_name: worktracker-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/worktracker
      SPRING_DATASOURCE_USERNAME: worktracker_user
      SPRING_DATASOURCE_PASSWORD: worktracker_pass
    ports:
      - "8080:8080"